### ISSUE TITLE
Error " replacement has length zero" 

### ISSUE THREAD

**Issue by diosarris** [rodazuero/gmapsdistance#10]
Hello,

I am using your gmapsdistance() function in a loop (I have my own Google API key). In general it is working fine but for e.g. when I try the below 

gmapsdistance("51.3238568,-0.754302", "-26.2041028,28.0473051", mode = "driving", key="MY KEY")

I get the error  

Error in data$Time[i] = as(xmlChildren(results$row[[1]])$duration_in_traffic[1]$value[1]$text,  : 
  replacement has length zero

Is there something wrong ? because the Google API does give an answer ( https://maps.googleapis.com/maps/api/distancematrix/json?origins=51.3238568,-0.754302&destinations=-26.2041028,28.0473051&mode=driving&language=en )

Thank you very much in advance

**Comment by MichaelChirico** [comment]
Hey @ZogD, typically the API returns a "duration in traffic" metric for driving directions. Your request, however, was over such a long distance (UK - South Africa) that traffic is only a very minor part of overall drive time, so Google simply returns a duration -- but `gmapsdistance` was still expecting `duration_in_traffic`. This should now be fixed.
