### ISSUE TITLE
Errors with mode = "driving" in combination with an API key

### ISSUE THREAD

**Issue by ghost** [rodazuero/gmapsdistance#14]
Hi,

When I use  the api key in my code and when the mode is set to driving , 
The gmapdistance function returns the following error 

 ```
Error in rowXML[[dur]] : subscript out of bounds 
4 .class1(object) 
3 as(rowXML[[dur]][1L]$value[1L]$text, "numeric") 
2 gmapsdistance(origin = coordmatrix$origin, destination = coordmatrix$destination, 
    combinations = "pairwise", mode = "driving", departure = 1477983600000) 
1 DistanceFunction() 
```

When i change the mode to bicycling, I only get the "exceeded daily request quota error, which i will try to work around 

I already checked this page: http://stackoverflow.com/questions/41133859/r-code-gmapsdistance ,
but i'm way to rookie to solve it in that way.

thx in advance

**Comment by Demetrio92** [comment]
Neat. The issue is confirmed and SO even provided a fix, yet nothing is done. I will submit a PR soonish.

**Comment by csograd** [comment]
Has there been any update to this in the CRAN yet? I'm still getting this error.

**Comment by Demetrio92** [comment]
@csograd, the repo is unmaintained. The dude finished grad school and probably moved on. 
Feel free to use `devtools::install_github("demetrio92/gmapsdistance")` -- it works. I am not intended to maintain the fork though. At least not for now. 

Please also check for alternatives here: https://github.com/ropensci/maptools

**Comment by csograd** [comment]
Thanks for the information and links.

**Comment by rodazuero** [comment]
Hi, as @Demetrio92 points out, I finished grad school but still trying to maintain the repo. We just changed the file and hopefully this will fix the issue.

**Comment by jcoopa** [comment]
@rodazuero, I'm having the same issue. Just tried it today no api key "driving" works fine. With Api key I get the same error "Error in rowXML[[dur]] : subscript out of bounds". 

Has any one found a work around? 
Thanks

**Comment by Demetrio92** [comment]
@jcoopa read above. Don't install the CRAN version. Do `devtools::install_github("rodazuero/gmapsdistance")`. Or if that still does not work my fork definitely does, but I won't maintain it further: `devtools::install_github("demetrio92/gmapsdistance")`

**Comment by jcoopa** [comment]
@Demetrio92 Thanks, That fixed it.

**Comment by ga47keb** [comment]
does anybody know how to get more than 2500 queries a day?

**Comment by Demetrio92** [comment]
@ga47keb offtopic, I guess. 
Nonetheless: without the API key, you don't get duration in traffic, but just the normal driving duration. And you can have unlimited requests (well, there probably is some undocumented hard limit)
If you need duration with traffic, then you can buy additional requests.

**Comment by Demetrio92** [comment]
devtools::install_github("rodazuero/gmapsdistance")
CRAN update coming soon
