### ISSUE TITLE
xmlParse Function

### ISSUE THREAD

**Issue by brasbilbit** [rodazuero/gmapsdistance#18]
After run gmapsdistance function, I tried to execute the below example, but the following error was showed >> **Error: could not find function "xmlParse"**

Are there anyway to get this function?

results = gmapsdistance(origin = "Washington+DC", 
                        destination = "New+York+City+NY", 
                        mode = "driving")

**Comment by rodazuero** [comment]
This package should have been installed when you installed gmapsdistance. I guess you can do it manually:

install.packages("XML")
library(XML)
