### ISSUE TITLE
gmapsdistance: character string is not in a standard unambiguous format error

### ISSUE THREAD

**Issue by bratamalya2** [rodazuero/gmapsdistance#21]
I have the following statement:
dist<-gmapsdistance(origin=from_loc, destination=to_loc, combinations="pairwise", mode="driving", key=get.api.key(), avoid="", departure = from_date_time, 
              traffic_model="best_guess",  arrival = to_date_time)

The statement does not execute and shows the following message:

Error in as.POSIXlt.character(x, tz, ...) : 
  character string is not in a standard unambiguous format

**Comment by Demetrio92** [comment]
Please, if you want to get help, provide a minimal reproducible example. 
Closed as outdated,but feel free to create a new one.
