### ISSUE TITLE
Error in function (type, msg, asError = TRUE)  :    SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by iamnagesh** [rodazuero/gmapsdistance#22]
I get this error when I try to use with an API key. What might be the reason?

```
> head(origins)
[1] "DELHI+DELHI"         "MUMBAI+MAHARASHTRA"  "BANGALORE+KARNATAKA" "CHENNAI+TAMILNADU"   "KOLKATA+WEST+BENGAL"
[6] "COCHIN+KERALA"      
> head(destination)
[1] "NEW+DELHI+DELHI"              "PORT+BLAIR+ANDAMAN+&+NICOBAR" "ACHANTA+ANDHRA+PRADESH"      
[4] "ADILABAD+ANDHRA+PRADESH"      "AGADUR+ANDHRA+PRADESH"        "AINAPUR+ANDHRA+PRADESH"   

> y <- gmapsdistance(origins,
+                    destination,
+                    mode = "driving", key = get.api.key(),
+                    shape = "wide")
Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: self signed certificate in certificate chain
```

**Comment by cyzhu** [comment]
I also got this error quite often... Sometimes close R and then restart would solve it but sometimes don't. Wonder if it has something to do with the API limits.

**Comment by cyzhu** [comment]
Don't understand why but this solves my problem:

set_config( config( ssl.verifypeer = 0L ) )

Reference:
https://stackoverflow.com/questions/24793863/devtoolsinstall-github-ignore-ssl-cert-verification-failure?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by Demetrio92** [comment]
Not sure what connection are you guys using, but that is not `gmapsdistance` issue.
