### ISSUE TITLE
Trying to use gmapsdistance to create a drive time matrix, but keep receiving an error

### ISSUE THREAD

**Issue by jasperc11** [rodazuero/gmapsdistance#23]
I am trying to get gmaps distance to output a drive time matrix originating at a hospital site which is the first cell in the site_latlon column and finishes at the geocoded lat + long data for 2000 GPs. 

I have already set.api.key() then I run the following code 

`results = gmapsdistance(origin = c(allsites_geocoded$site_latlon[1]), destination = c(allgps_geocoded$gp_latlon),combinations = "all", mode = "driving")`

Every time I run this code I get this error in return.
Error in UseMethod("xmlChildren") : 
  no applicable method for 'xmlChildren' applied to an object of class "NULL"

can anyone assist?

**Comment by IbraFal** [comment]
Just check if your 2000 entries don't have any any special character or space. I ran into the same issue  because of a stupid #.

**Comment by Demetrio92** [comment]
Fixed.
`devtools::install_github("rodazuero/gmapsdistance")`
CRAN update coming soon.
