### ISSUE TITLE
Every call fails...

### ISSUE THREAD

**Issue by ehud** [rodazuero/gmapsdistance#27]
Any of the examples on the readme end up with the following errors:

Opening and ending tag mismatch: META line 2 and HEAD
Specification mandate value for attribute noshade
attributes construct error
Couldn't find end of Start Tag HR line 9
Opening and ending tag mismatch: LI line 16 and UL
Opening and ending tag mismatch: UL line 15 and P
Opening and ending tag mismatch: A line 31 and a
Opening and ending tag mismatch: A line 33 and a
Specification mandate value for attribute noshade
attributes construct error
Couldn't find end of Start Tag HR line 37
Opening and ending tag mismatch: BR line 36 and BODY
Opening and ending tag mismatch: P line 13 and HTML
Premature end of data in tag P line 10
Premature end of data in tag BODY line 6
Premature end of data in tag HEAD line 2
Premature end of data in tag HTML line 2

**Comment by rodazuero** [comment]
Not sure why are you getting the error. I just ran the basic example and it seems is working fine. 

```
results = gmapsdistance(origin = "Washington+DC", destination = "New+York+City+NY",  mode = "driving")
> results
$Time
[1] 13811

$Distance
[1] 361720

$Status
[1] "OK"
```



I would suggest to re-install it from CRAN and then from github if it is not running.

**Comment by ehud** [comment]
I tried both installations; also upgraded R.

**Comment by ehud** [comment]
I turns out that this was the result of the proxy password being wrong in the environment variables. Sorry about that.
