### ISSUE TITLE
 Error in gmapsdistance(origin, destination, mode = "driving") :    Google API returned an error: You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=

### ISSUE THREAD

**Issue by AntonioZS** [rodazuero/gmapsdistance#30]
Hola buenas,
Os comento mi problema...Tengo un Uso del servicio de matriz de distancia en el plan estándar con una facturación asociada habilitada para acceder a las cuotas diarias por un costo de USD 0,50 cada 1000 elementos adicionales, hasta 100 000 elementos diarios. Sin embargo, tras realizar un número aproximado de unas 1000-2000 elementos (con 10 orígenes y 10 destinos por petición, es decir, entre 10-20 llamadas al Serrvidor Google Maps )recibo el siguiente xml de rerspuesta de la función gmpasdistance:

**<DistanceMatrixResponse>
 <status>OVER_QUERY_LIMIT</status>
    <error_message>
        You have exceeded your daily request quota for this API. We recommend registering for a key at the 
        Google Developers Console: https://console.developers.google.com/apis/credentials?project=_
    </error_message>
</DistanceMatrixResponse>**

Compruebo que este error no se debe a que estoy accediendo a demasiadas peticiones por segundo sobre el servidor, ya que tras esperar unos segundos, de nuevo pruebo con 1 solo Origen-Destino, obteniendo el mismo mensaje de error. Si el plan teóricamente me permite realizar un máximo de 100.000 peticiones diarias (0,50 USD por cada 1000 adicionales partiendo de las 2500 gratuitas diarias).... 
¿Por qué no me está dejando acceder a dicho servicio de pago por solicitudes adicionales?  

Agradecería muchísimo vuestra ayuda con este problema que estoy teniendo...

Saludos y muchas gracias de antemano.

**Comment by Demetrio92** [comment]
@AntonioZS translate.google.com says: 

> Has excedido tu cuota de solicitud diaria para esta API. Recomendamos registrarse para obtener una clave en el
> Google Developers Console: https://console.developers.google.com/apis/credentials?project=_

was this helpful?
