### ISSUE TITLE
Example #1 throws an error

### ISSUE THREAD

**Issue by sanaani** [rodazuero/gmapsdistance#31]
results = gmapsdistance(origin = "Washington+DC", destination = "New+York+City+NY", mode = driving")
_**Error in rowXML[[dur]] : subscript out of bounds**_

What's wrong?

**Comment by sanaani** [comment]
I'm running Ubuntu 16.04.3 LTS

**Comment by AzizKhiyami** [comment]
I get the same problem:

Error in rowXML[[dur]] : subscript out of bounds
In addition: Warning message:
In strptime("1970-01-01 00:00:00", "%Y-%m-%d %H:%M:%OS", tz = "GMT") :
  unknown timezone 'zone/tz/2018c.1.0/zoneinfo/America/Los_Angeles'

I'm running it via R-Studio on  MacBook Pro running macOS High Sierra

**Comment by rodazuero** [comment]
Hi, thanks for your comments. Have you tried running the github version? You can install and run it following this commands:

 install.packages("devtools")
devtools::install_github("rodazuero/gmapsdistance")
library(gmapsdistance)

Let me know if the problem persists but I think it should run fine.

**Comment by AzizKhiyami** [comment]
Hi, the github version seems to have fixed it!

Thanks
