### ISSUE TITLE
Slow google API Responses

### ISSUE THREAD

**Issue by marco-vene** [rodazuero/gmapsdistance#5]
Hi,

Thanks for your awesome package. I am trying to ask pairwise distances with the code below, where or and des are vectors of more than 100 thousands elements:

results = gmapsdistance(origin = or, destination = des, mode = "driving", combinations = "pairwise ")

The code seems to handle a single couple of coordinates in around 6.7 seconds, that would mean around 2 weeks of time to get the results. :) 

Do you know if there are ways of speed up drastically this process?
I have an API key already.

Best,

**Comment by njanetos** [comment]
You'd want to submit some sort of batch request. The [Google API description](https://developers.google.com/maps/documentation/distance-matrix/intro) suggests that multiple destinations and starting points can be submitted by separating them with the pipe (`|`) symbol. I don't know how the package will handle that though, but you might try it.

Separately from that, it looks like the function `gmapsdistance` accepts a parameter called `combinations`, and the origin and destination parameters are allowed to be vectors of strings. However, it looks from the source code that the package simply iterates over the vectors and sends a request separately for each one. It would be a good improvement to the package for it to automatically batch such requests.

**Comment by MichaelChirico** [comment]
See #12 as well which I think will speed this up.
