### ISSUE TITLE
NOT FOUND

### ISSUE THREAD

**Issue by philipgladwin** [rodazuero/gmapsdistance#6]
Hi,
Sometimes I find the status returned as NOT_FOUND using e.g. 
JT = gmapsdistance(
   origin="AL10",  
   destination = "PE85AQ",
   mode = "driving",
   shape="long",
   key=APIkey)

Is this a problem in Google World or with this package?

Al10 represents the "outcode" which is the first part of the UK postcode.
PE85AQ represents a full UK postcode.
I have  valid API key.
Thank you.

Phil,

**Comment by njanetos** [comment]
Hi,

When I run your query it returns

```
JT
$Time
[1] NA

$Distance
[1] NA

$Status
[1] "ROUTE_NOT_FOUND"
```

It appears from the source that `ROUTE_NOT_FOUND` is returned by Google Maps, not by the package. So it's a problem with Google Maps.
