### ISSUE TITLE
It is not available for R version 3.3.1.

### ISSUE THREAD

**Issue by Thepparit** [rodazuero/gmapsdistance#7]
I would like to use this package but it is not available for R version 3.3.1.
![image](https://cloud.githubusercontent.com/assets/4102337/19502843/667da29a-95a7-11e6-9425-0fe04048e1aa.png)

**Comment by njanetos** [comment]
I don't have 3.3.1 but have you tried installing it from github directly?

```
install.packages("devtools")
library(devtools)

install_github("rodazuero/gmapsdistance")
```

**Comment by Thepparit** [comment]
Thank you very much for your answer. But it does not work.

Best regards,

John

**Comment by rodazuero** [comment]
@Thepparit 
What happens when you try the solution suggested by @njanetos ? Do you get an error message?

**Comment by njanetos** [comment]
@Thepparit Check that you've spelled the name of the package, which is `gmapsdistance`, correctly.
