### ISSUE TITLE
Request quotas?

### ISSUE THREAD

**Issue by mbacou** [rodazuero/gmapsdistance#9]
Google Maps Distance Matrix API allows passing multiple origins/destinations in 1 API call. Does someone know if that's considered 1 request (per Google's quota) or multiple requests? I just hit my daily quota passing 22 requests (of 100 destinations each), that seems odd.

**Comment by njanetos** [comment]
That's odd. According to the online documentation it's per-request. 

Are you using the API directly to make multiple requests? (I.e., separating multiple destinations with the pipe symbol in the URL.) Or are you using the package directly (I.e., passing a vector of destinations and origins into R?) 

If it's the latter (and correct me if I'm wrong, @rodazuero), it looks from the source code that the package handles this by iterating over all the origins / destinations and making a separate request for each one. (See also #5 for a similar issue.) So, that would exceed your usage limit very quickly, as well as take quite a long time to finish. 

If it's the former then I'm not sure what it could be.

**Comment by mbacou** [comment]
Right, I was using the package and passing a vector of origins and destinations. Might try to interact with the API directly using `httr` instead and pipes.

**Comment by njanetos** [comment]
@rodazuero you should close #5 and leave this issue open as a reminder to someday bundle requests.

**Comment by mbacou** [comment]
Actually with `httr` and piped requests, I also hit my 2,500 daily quota in a few requests, so not certain Google's documentation is quite correct.

**Comment by njanetos** [comment]
The specific text is

> Google Maps web service APIs include 2,500 free requests per day, calculated as the sum of your client-side requests (made via the Google Maps JavaScript API services) and your server-side requests. To access higher daily quotas (up to 100,000 per day), we offer pay-as-you-go pricing.

I wonder what a 'server-side request' is.

**Comment by pedrokost** [comment]
They have corrected the working now:

> 2,500 free elements per day, calculated as the sum of client-side and server-side queries.

and 

> Each query sent to the Google Maps Distance Matrix API is limited by the number of allowed elements, where the number of origins times the number of destinations defines the number of elements.

**Comment by mbacou** [comment]
Thanks for the info!
